quarkus.application.name=onion-web
quarkus.package.jar.add-runner-suffix=false
quarkus.package.jar.type=uber-jar
#quarkus.http.root-path=/onion-web
# Logging configuration
## Console logging enabled by default
quarkus.log.console.enabled=true
quarkus.log.console.level=DEBUG
## REST Client Logging
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=10000
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG