onion-app.storage.path=${ONION_APP_STORAGE_PATH:/tmp/onion-app-storage}
quarkus.http.port=${ONION_APP_SERVER_PORT:8080}
quarkus.application.name=onion-web
quarkus.package.jar.add-runner-suffix=false
quarkus.package.jar.type=uber-jar
#quarkus.http.root-path=/onion-web
#Authentication
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.plantApiClient=${ONION_APP_API_PASSWORD}
quarkus.http.limits.max-form-attribute-size=50M
quarkus.http.auth.basic=true
quarkus.http.auth.permission.permit1.paths=/plant/ui/*,/static/*
quarkus.http.auth.permission.permit1.policy=permit
quarkus.http.auth.permission.permit1.methods=GET
quarkus.http.auth.permission.authenticated1.paths=/plant/api/*
quarkus.http.auth.permission.authenticated1.policy=authenticated
quarkus.http.auth.permission.authenticated1.methods=POST
# Logging configuration
## Console logging enabled by default
quarkus.log.console.enabled=true
quarkus.log.console.level=ERROR
%test.onion-app.raw-to-process.path=g:\\Data\\raw-to-process